[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dndoc"
version = "0.1.0"
description = "A CLI D&D character sheet replacement"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name="Nathan Kawamoto", email="njkawamoto@gmail.com" }
]
dependencies = []

[project.scripts]
dndoc = "dndoc.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["dndoc"]
